Repository open-cluster-management-io/multicloud-operators-subscription, pull requests merged in 2022-06, with the labels that each got.

#185 Add test case to validate k8s label
  pkg/placementrule/utils/label_test.go
Labels: lgtm

#188 Add tests for Gitrepo utils
  pkg/utils/gitrepo_test.go
Labels: approved, lgtm

#189 Migrate Ginkgo to v2
  Makefile.prow
  README.md
  build/e2e-kc.sh
  go.mod
  go.sum
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hook_test.go
  pkg/controller/mcmhub/hub_git_test.go
  pkg/subscriber/git/git_subscriber_suite_test.go
  pkg/subscriber/git/git_subscriber_test.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_suite_test.go
  pkg/subscriber/helmrepo/helmrepo_subscriber_test.go
  pkg/synchronizer/kubernetes/sync_appsubstatus_test.go
  pkg/synchronizer/kubernetes/sync_suite_test.go
  pkg/synchronizer/kubernetes/synchronizer_test.go
  pkg/utils/subscription_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, lgtm

#195 New service account for some application pods
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved, lgtm

#196 Add missing rules for multicluster-applications SA
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved, lgtm

#197 Update rules requires for app webhook
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved, lgtm

#199 Git missing gitops status rule
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved

#200 Avoid deleting manifestwork which contains the same label but belongs…
  pkg/controller/mcmhub/propagate_manifestwork.go
Labels: approved, lgtm

#201 Remove hardcoded user uid from dockerfile
  build/Dockerfile
  build/Dockerfile.prow
Labels: approved, lgtm

#203 Revert removal of user uid from dockerfile
  build/Dockerfile
  build/Dockerfile.prow
Labels: approved

#202 add unit test for object store subscriber
  pkg/subscriber/objectbucket/objectbucket_subscriber_test.go
Labels: approved

#198 Update OWNERS
  OWNERS
Labels: approved, lgtm
