Repository open-cluster-management-io/multicloud-operators-subscription, pull requests merged in 2022-02, with the labels that each got.

#78 Cleanup deployables for old subscriptions
  pkg/apis/addtoscheme_apps_v1.go
  pkg/apis/apps/deployable/v1/deployable_types.go
  pkg/apis/apps/deployable/v1/doc.go
  pkg/apis/apps/deployable/v1/register.go
  pkg/apis/apps/deployable/v1/zz_generated.deepcopy.go
  pkg/controller/mcmhub/deployable.go
  pkg/controller/mcmhub/hook_suite_test.go
  pkg/controller/mcmhub/hub.go
  pkg/controller/mcmhub/mcmhub_controller_suite_test.go
Labels: approved, lgtm

#79 Remove DNS check for Helm subscription
  pkg/controller/mcmhub/metaupdate.go
Labels: approved, lgtm

#80 appstatus deployed on the local-cluster should have the same appsub name
  pkg/subscriber/git/git_subscriber.go
  pkg/subscriber/objectbucket/objectbucket_subscriber.go
  pkg/synchronizer/kubernetes/sync_appsubstatus.go
  pkg/synchronizer/kubernetes/synchronizer.go
Labels: approved

#83 set default value for helmrelease chart directory
  deploy/common/0000_03_clusters.open-cluster-management.io_placements.crd.yaml
  deploy/common/0000_04_clusters.open-cluster-management.io_placementdecisions.crd.yaml
  pkg/controller/mcmhub/metaupdate.go
  pkg/helmrelease/controller/helmrelease/helmrelease_controller.go
  pkg/helmrelease/controller/helmrelease/helmreleasemgr.go
Labels: approved, lgtm

#86 check other cluster role bindings for subscription admin
  pkg/utils/gitrepo.go
  pkg/utils/gitrepo_test.go
Labels: approved, lgtm, do-not-merge/hold

#87 Use ManifestWork delete policy to keep the managed cluster appsub namespace
  build/e2e-kc.sh
  pkg/controller/mcmhub/propagate_manifestwork.go
  pkg/placementrule/controller/placementrule/placementrule_controller_test.go
  test/e2e/cases/03-keep-namespace/channel.yaml
  test/e2e/cases/03-keep-namespace/clusterset.yaml
  test/e2e/cases/03-keep-namespace/clustersetbinding.yaml
  test/e2e/cases/03-keep-namespace/placement.yaml
  test/e2e/cases/03-keep-namespace/subscription.yaml
Labels: approved, lgtm

#89 code refactoring
  pkg/utils/gitrepo.go
Labels: approved

#88 Remove cleanup of deployables
  pkg/controller/mcmhub/hub.go
  pkg/placementrule/controller/placementrule/placementrule_controller_test.go
Labels: approved, lgtm

#90 Allow appsub controllers to be able to run outside of cluster
  cmd/appsubsummary/exec/manager.go
  cmd/appsubsummary/exec/options.go
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  cmd/placementrule/exec/manager.go
  cmd/placementrule/exec/options.go
  pkg/utils/subscription.go
Labels: approved, lgtm

#91 Add agent-install-all flag to subscription addon
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  pkg/addonmanager/addon.go
  pkg/addonmanager/addon_test.go
Labels: approved, lgtm
