Repository open-cluster-management-io/multicloud-operators-subscription, pull requests merged in 2025-01, with the labels that each got.

#417 bump golang.org/x/crypto and golang.org/x/net
  deploy/ocm/verify_app_addon.sh
  go.mod
  go.sum
Labels: approved

#418 Implement Objectstore TLS support
  OWNERS
  pkg/controller/mcmhub/hub.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_item.go
  pkg/subscriber/objectbucket/objectbucket_subscriber_test.go
  pkg/utils/aws/objectstore.go
  pkg/utils/aws/objectstore_test.go
Labels: approved, lgtm, do-not-merge/invalid-owners-file

#419 add gitops addon manifests
  deploy/olm-catalog/multicluster-operators-subscription/manifests/gitops-addon.addonTemplates.yaml
  deploy/olm-catalog/multicluster-operators-subscription/manifests/gitops-addon.clusterManagementAddon.yaml
Labels: approved, lgtm

#420 Remove limits for current hub controllers
  deploy/olm-catalog/multicluster-operators-subscription/manifests/multicluster-operators-subscription.clusterserviceversion.yaml
Labels: approved
